package(default_visibility = ["//visibility:public"])

filegroup(
    name = "angularProject",
    srcs = glob(["**"]) + [
        "//angular-real-world/angular/src/app1:src",
        "//angular-real-world/angular/src/app2:src",
        "//angular-real-world/angular/src/app3:src",
        "//angular-real-world/angular/src/app4:src",
        "//angular-real-world/angular/src/app5:src",
        "//angular-real-world/angular/src/app6:src",
        "//angular-real-world/angular/src/app7:src",
        "//angular-real-world/angular/src/app8:src",
        "//angular-real-world/angular/src/app9:src",
        "//angular-real-world/angular/src/app10:src",
        "//angular-real-world/angular/src/organisme1:organisme1",
        "//angular-real-world/angular/src/organisme2:organisme2",
        "//angular-real-world/angular/src/organisme3:organisme3",
        "//angular-real-world/angular/src/organisme4:organisme4",
        "//angular-real-world/angular/src/molecule1:molecule1",
        "//angular-real-world/angular/src/molecule2:molecule2",
        "//angular-real-world/angular/src/molecule3:molecule3",
        "//angular-real-world/angular/src/molecule4:molecule4",
        "//angular-real-world/angular/src/atom1:atom1",
        "//angular-real-world/angular/src/atom2:atom2",
        "//angular-real-world/angular/src/atom3:atom3",
        "//angular-real-world/angular/src/atom4:atom4"
    ]
)
